version: 2

jobs:

  build-test:

    docker:
      - image: circleci/php:7.1-node-browsers

    working_directory: ~/unit

    steps:

      - checkout

      - run: sudo apt-get install -y libsqlite3-dev zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update

      - run: composer install -n --prefer-dist
      - run: ./vendor/bin/phpunit
      - run: vendor/bin/phpcs --standard=PSR2 src


workflows:
  version: 2
  build-check:
    jobs:
      - build-test:
          filters:
            branches:
              only:
                - master
                - develop
